language: java

jdk:
  - openjdk7
  - oraclejdk7

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dcheckstyle.skip=true -B -V

after_success:
  - mvn clean cobertura:cobertura coveralls:report
